### ISSUE TITLE
Didn't work on OSX Yosemite with openSSL 0.9.8 and 1.0.2

### ISSUE THREAD

**Issue by Miasma87** [glv2/bruteforce-salted-openssl#1]
Hi !
Can you tak a look at this log please.
I don't understand why it didn't work.
If I found anything I will put it here.

Regards.

gcc  -g -O2   -o bruteforce-salted-openssl src/bruteforce-salted-openssl.o  -lcrypto -lpthread 
Undefined symbols for architecture x86_64:
  "_EVP_CIPHER_do_all_sorted", referenced from:
      _list_algorithms in bruteforce-salted-openssl.o
      _main in bruteforce-salted-openssl.o
  "_EVP_MD_do_all_sorted", referenced from:
      _list_algorithms in bruteforce-salted-openssl.o
      _main in bruteforce-salted-openssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Miasma87** [comment]
That's ok, it's work now.
The problem was all those crappy autotools and blablabla...
I just type "clang -o bruteforce-salted-openssl bruteforce-salted-openssl.c -lcrypto -lpthread -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include" and everything went well :)

**Comment by nikolaydyankov** [comment]
Sorry to join this discussion more than a year later, but I was getting the same error, did the "clang" command that @Miasma87 mentioned, but I'm still getting the "Undefined symbols for architecture x86_64"

Running OSX El Capitan.
